const dimensions = [
  {
    id: "dataQuality",
    name: "Governing Data Quality",
    shortName: "Data Quality",
  },
  {
    id: "availability",
    name: "Enabling availability of data through Integration & architecture",
    shortName: "Integration & Architecture",
  },
  {
    id: "accountability",
    name: "Accountability, Risk & Compliance controls",
    shortName: "Risk & Compliance",
  },
] as const;

type DimensionId = (typeof dimensions)[number]["id"];

type Stage = {
  name: string;
  practices: Record<DimensionId, string[]>;
};

const stages: Stage[] = [
  {
    name: "Initial",
    practices: {
      dataQuality: [
        "Metadata is unstructured and unstandardised for AI purposes",
        "Data lifecycle is not monitored or governed for AI purposes",
        "Monitoring and measurements are not governed for AI purposes",
      ],
      availability: [
        "Data architecture does not support training models or supporting active models with data",
        "Data integration and interoperability is not governed to reliably share or exchange data for training models or supporting active models with data",
      ],
      accountability: [
        "Data security protocols are ad hoc and unstandardised",
        "Stewardship and accountability responsibilities are undefined or not optimised for AI",
        "Data is not aligned with organisational objectives",
        "Data compliance and external audit procedures are not formally established",
      ],
    },
  },
  {
    name: "Isolated AI enabled",
    practices: {
      dataQuality: [
        "Critical AI metadata standards",
        "Structured metadata classification standards",
        "Data quality metadata measurement standards",
        "Data lineage metadata standards",
        "Data source collection policies",
        "Data quality and bias monitoring procedures",
      ],
      availability: [
        "Local data pipeline standards",
        "Data repository standards",
        "Storage architectures defined",
        "Federated storage governance",
        "ETL standards",
        "API-based data access control policies",
        "Intra-departmental data integration rules",
        "Inter-departmental data integration rules",
        "Inter-departmental data synchronization protocols",
      ],
      accountability: [
        "Data access compliance policy to laws and regulations",
        "Data collection compliance to laws and regulations",
        "Stakeholder data usage approval procedures",
        "Defined data access authority roles",
        "Departmental data stewards roles assigned",
        "Departmental data stewardship responsibilities defined",
      ],
    },
  },
  {
    name: "Organisational AI enabled",
    practices: {
      dataQuality: [
        "Metadata organisation-wide standardisation",
        "Metadata catalog standardisation",
        "Defined data drift monitoring lifecycle procedures",
        "Standardised continuous procedures for data quality and embedded bias monitoring policies",
        "Training data benchmarking standards",
      ],
      availability: [
        "Organisation training data repository architecture defined",
        "Standards for unstructured data transformation pipelines",
        "Standards for organisation data mining procedures",
        "Standards for organisation process mining procedures",
      ],
      accountability: [
        "Standardised adversarial malicious actor security",
        "Data steward council",
        "Standardised organisation data governance training procedures governed",
        "Reference to data governance standards",
        "Communication standards",
        "Organisation AI data stewardship defined",
        "Organisation AI data alignment strategy defined",
      ],
    },
  },
  {
    name: "Autonomous Organisation Agents Optimised",
    practices: {
      dataQuality: [
        "Metadata includes agent data usage",
        "Metadata includes quality characteristics of data generated by AI",
        "Metadata includes traceability to source for data generated by AI",
        "Autonomous data quality controls",
        "Autonomous real-time bias drift correction",
      ],
      availability: [
        "Defined agent orchestration architecture",
        "Event-driven governance architecture policies",
        "Agent-to-agent interoperability protocols",
        "Autonomous data routing policies",
      ],
      accountability: [
        "Data stewardship for autonomous agents",
        "Tamper-resistant data lineage governance",
        "Rules for agent data access to context and semantic data",
      ],
    },
  },
];

const questionnaireSections = stages.map((stage) => ({
  title: stage.name,
  dimensions: dimensions.map((dimension) => ({
    id: `${stage.name}-${dimension.id}`,
    title: dimension.shortName,
    questions: stage.practices[dimension.id],
  })),
}));

const totalPractices = stages.reduce(
  (sum, stage) =>
    sum +
    dimensions.reduce(
      (stageTotal, dimension) => stageTotal + stage.practices[dimension.id].length,
      0,
    ),
  0,
);

export default function Home() {
  return (
    <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,_rgba(255,255,255,0.95),_rgba(235,242,237,0.88)_48%,_rgba(214,226,219,0.8))] px-4 py-8 text-slate-950 sm:px-6 lg:px-8">
      <div className="mx-auto flex w-full max-w-7xl flex-col gap-6">
        <section className="rounded-[2rem] border border-white/70 bg-white/85 p-6 shadow-[0_24px_80px_rgba(53,75,64,0.12)] backdrop-blur md:p-8">
          <div className="mb-6 flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
            <div>
              <p className="text-sm font-medium uppercase tracking-[0.24em] text-emerald-700">
                Assessment Overview
              </p>
              <h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950 md:text-4xl">
                Maturity Matrix
              </h1>
              <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600 md:text-base">
                The matrix reflects your 4 maturity stages across 3 dimensions, with each practice mirrored in the questionnaire below.
              </p>
            </div>
            <div className="rounded-2xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-sm text-emerald-900">
              4 stages · 3 dimensions · {totalPractices} practices
            </div>
          </div>

          <div className="overflow-x-auto rounded-[1.5rem] border border-slate-200 bg-slate-50">
            <div className="min-w-[72rem] overflow-hidden">
              <div className="grid grid-cols-[15rem_repeat(3,minmax(0,1fr))] border-b border-slate-200 bg-slate-100 text-sm font-semibold text-slate-700">
                <div className="px-5 py-4">Dimensions / Stages</div>
                {dimensions.map((dimension) => (
                  <div key={dimension.id} className="border-l border-slate-200 px-5 py-4 text-center">
                    {dimension.name}
                  </div>
                ))}
              </div>

              {stages.map((stage, stageIndex) => (
                <div
                  key={stage.name}
                  className="grid grid-cols-[15rem_repeat(3,minmax(0,1fr))] bg-white text-sm text-slate-700"
                >
                  <div
                    className={`bg-[linear-gradient(180deg,_rgba(140,185,226,0.7),_rgba(76,132,188,0.92))] px-5 py-6 text-white ${
                      stageIndex < stages.length - 1 ? "border-b border-slate-200" : ""
                    }`}
                  >
                    <div className="text-base font-semibold leading-6">{stage.name}</div>
                  </div>

                  {dimensions.map((dimension) => (
                    <div
                      key={`${stage.name}-${dimension.id}`}
                      className={`border-l border-slate-200 px-5 py-6 ${
                        stageIndex < stages.length - 1 ? "border-b border-slate-200" : ""
                      }`}
                    >
                      <ul className="ml-4 space-y-2 text-sm leading-6 text-slate-700">
                        {stage.practices[dimension.id].map((practice) => (
                          <li key={practice} className="list-disc marker:text-emerald-600">
                            {practice}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="rounded-[2rem] border border-white/70 bg-white/85 p-6 shadow-[0_24px_80px_rgba(53,75,64,0.12)] backdrop-blur md:p-8">
          <div className="mb-6 flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
            <div>
              <p className="text-sm font-medium uppercase tracking-[0.24em] text-emerald-700">
                Questionnaire
              </p>
              <h2 className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">
                Check Questions
              </h2>
              <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600 md:text-base">
                Every practice from the matrix is listed below as a checkbox so the assessment can later be scored from the same model.
              </p>
            </div>
            <div className="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700">
              {totalPractices} questionnaire items
            </div>
          </div>

          <form className="space-y-5">
            {questionnaireSections.map((section) => (
              <fieldset
                key={section.title}
                className="rounded-[1.5rem] border border-slate-200 bg-slate-50 p-5"
              >
                <legend className="px-2 text-base font-semibold text-slate-950">
                  {section.title}
                </legend>
                <div className="mt-4 grid gap-4 lg:grid-cols-3">
                  {section.dimensions.map((dimension) => (
                    <div key={dimension.id} className="rounded-[1.25rem] bg-white p-4 shadow-sm">
                      <h3 className="text-sm font-semibold uppercase tracking-[0.16em] text-slate-600">
                        {dimension.title}
                      </h3>
                      <div className="mt-3 space-y-3">
                        {dimension.questions.map((question) => (
                          <label
                            key={question}
                            className="flex items-start gap-3 rounded-2xl border border-transparent bg-slate-50 px-4 py-3 text-sm leading-6 text-slate-700 transition-colors hover:border-emerald-200"
                          >
                            <input
                              type="checkbox"
                              className="mt-1 h-4 w-4 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500"
                            />
                            <span>{question}</span>
                          </label>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </fieldset>
            ))}

            <div className="flex justify-end pt-2">
              <button
                type="button"
                className="rounded-2xl bg-slate-950 px-6 py-3 text-sm font-semibold text-white transition-transform duration-200 hover:-translate-y-0.5 hover:bg-emerald-700 focus:outline-none focus:ring-2 focus:ring-emerald-400 focus:ring-offset-2"
              >
                Update
              </button>
            </div>
          </form>
        </section>
      </div>
    </main>
  );
}
